.TH PSEARCH "1" "June 2012" "psearch 2.0.2"
.SH NAME
psearch \- search the FreeBSD ports
.SH SYNOPSIS
\fBpsearch\fR [\fIoptions\fR] \fIPATTERN\fR [\fIPATTERN\fR \fI...\fR]
.SH DESCRIPTION
Lists ports whose description matches \fIPATTERN\fR. \fIPATTERN\fR is a
case-insensitive regular expression.
.PP
If more than one pattern is given, a port description has to match all of them
for the port to be listed. If \fB\-o\fR is given, a single pattern match
suffices instead.
.PP
By default, the name and the short description are searched. If \fB\-s\fR is
given, the long description is searched as well, which slows things down a
lot. This can be compensated for by limiting searches to a port category with
\fB\-c\fR, thus reducing the number of pkg-plist files that need to be
searched.
.PP
\fBpsearch\fR uses IEEE Std 1003.2 (``POSIX.2'') regular expressions as explained by 
.BR re_format (7) .
.SH OPTIONS
.TP
\fB\-V\fR, \fB\-\-version\fR
Show program's version number and exit.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a brief help message explaining the options and exit.
.TP
\fB\-c\fR \fICATEGORY\fR, \fB\-\-category\fR=\fICATEGORY\fR
Only search for ports in \fICATEGORY\fR. Speeds up searching,
especially when \fB\-\-search_long\fR is also specified.
.TP
\fB\-f\fR \fIFILE\fR, \fB\-\-file\fR=\fIFILE\fR
Path to INDEX file. Defaults to the standard location of the INDEX file
on the FreeBSD system that \fBpsearch\fR runs on. Non-standard locations
given in /etc/make.conf are ignored.
.TP
\fB\-l\fR, \fB\-\-long\fR
Display the long description (pkg\-descr file) for any match found. They are
not searched however, unless \fB\-\-search_long\fR is also given.
.TP
\fB\-m\fR, \fB\-\-maintainer\fR
Display the maintainer's email address instead of the short description
for any match found, and switch on searching the maintainer's email address.
Specifying this parameter and searching for \fBports@freebsd.org\fR displays
all unmaintained ports.
.TP
\fB\-n\fR, \fB\-\-name\fR
Print canonical name of a port, including its version.
.TP
\fB\-o\fR, \fB\-\-or\fR
List ports whose description match any \fIPATTERN\fR, instead of requiring it
to match all of them.
.TP
\fB\-s\fR, \fB\-\-search_long\fR
Search long descriptions (pkg\-descr file), which slows down
searching. The long descriptions are not displayed however, unless
\fB\-\-long\fR is also given.
.TP
\fB\-v\fR \fIINVERSE_PATTERN\fR, \fB\-\-inverse\fR=\fIINVERSE_PATTERN\fR
Searches for ports that do not match \fIINVERSE_PATTERN\fR. May be
specified several times.
.SH SEE ALSO
.BR re_format (7)
.SH BUGS
Any relevant values stored in environment variables or /etc/make.conf are ignored.
This means that if your INDEX file does not reside in /usr/ports, you'll need to use
the \fB-f\fR option when running \fBpsearch\fR.
.SH AUTHOR
Benjamin Lutz (http://public.xdi.org/=Benjamin.Lutz)
